### Post Append
POST http://localhost:8080/posts
Content-Type: application/json

{
  "content": "This is content!"
}

### Get Single Post
GET http://localhost:8080/posts/1
Content-Type: application/json


### Post Append
POST http://localhost:8080/posts/only-content
Content-Type: application/json

{
  "content": "This is content!"
}